include: package:very_good_analysis/analysis_options.yaml

analyzer:
  # exclude:
  #   - "**/*.g.dart"


linter:
  rules:
    public_member_api_docs: false
    prefer_int_literals: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    sort_pub_dependencies: false
    prefer_constructors_over_static_methods: false
    no_leading_underscores_for_local_identifiers: false
  

