targets:
  $default:
    sources:
      exclude: ["example/**", "test/**"]
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - avoid_init_to_null



