name: UI-KIT CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
   name: Static code analysis
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v1
     - run: git submodule update --init --recursive
     - run: flutter pub get
     - run: cd packages/nomo-router && flutter pub get
     - run: cd ..
     - run: cd ..
     - name: Lint analysis
       run: flutter analyze

  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1

    - name: Install dartdoc
      run: flutter pub global activate dartdoc

    - name: Generate API docs
      run: flutter pub global run dartdoc

    - name: Copy Docs output
      run: cp -R doc/api docs

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTION_GITHUB_TOKEN }}
        publish_dir: ./docs
