name: UI-KIT CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
   name: Static code analysis
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v1
     - run: git submodule update --init --recursive
     - run: flutter pub get
     - name: Lint analysis
       run: flutter anaylze
     - name: Run tests
       run: flutter test
     
